### ISSUE TITLE
Error: No property 'icon_size' in property list (or its value was undefined)

### ISSUE THREAD

**Issue by jepst** [user501254/TouchpadIndicator#5] opened 2016-06-11 18:38 UTC
Extension does not load properly after login. In Looking Glass I get the error message "Error: No property 'icon_size' in property list (or its value was undefined)". Reloading Gnome Shell brings the extension back on.
Gnome-shell 3.20.2-3 on Debian Testing

**Comment by user501254** [comment] 2016-06-11 18:48
@jepst 
Hi, this is a duplicate of [gnome-shell-extension-touchpad-indicator/issues/53](https://github.com/orangeshirt/gnome-shell-extension-touchpad-indicator/issues/53#issue-114494126).
Some additional details would be helpful.

How often this happens? (eg.: random, every-time, on some particular event, can't say)
Does turning off _Show Icon In Main Panel_ under settings still cause the issue?

**Comment by jepst** [comment] 2016-06-11 19:00
I resubmitted the issue because it seems that the old repo, and its issues, are dead.

This problem happens when gnome-shell is started or restarted. Turning off "Show Icon" does not solve the problem.

The issue seems to be fixed with this commit: https://github.com/jepst/TouchpadIndicator/commit/9dd64c70ebddb5e285862bc0c262366ac714dee9

But I'm not sure if that's the ideal solution, and I haven't tested it with versions of gnome-shell less than 3.20-2-3. Nevertheless, it definitely seems to be an issue with the location of the constant defining the icon size

**Comment by user501254** [comment] 2016-06-12 06:09
Thanks for the info.
Could you also tell me if you have _Show notification_ switch turned on under settings _Auto Switch_ tab?
If yes, does turning it off and restarting GNOME Shell still give the same error message?

**Comment by user501254** [comment] 2016-08-27 06:47
Fixed in 9dd64c70ebddb5e285862bc0c262366ac714dee9.

**Closed by user501254** 2016-08-27 06:47 UTC
