### ISSUE TITLE
Gnome 3.32

### ISSUE THREAD

**Issue by kamilizmer** [user501254/TouchpadIndicator#36] opened 2019-04-25 20:21 UTC
After installing unstable version for 3.32 I have the same issue: Error.

**Comment by user501254** [comment] 2019-04-27 05:47
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/34

**Comment by user501254** [comment] 2019-04-27 05:48
Please see https://github.com/user501254/TouchpadIndicator/issues/35#issuecomment-486425301

**Closed by user501254** 2019-04-27 05:47 UTC
Labels: duplicate
