### ISSUE TITLE
Hope to add shortcuts to quickly set up

### ISSUE THREAD

**Issue by Yehun** [user501254/TouchpadIndicator#25] opened 2018-04-11 02:26 UTC
Hope to add hot key to quickly set up,
Let users define their own shortcut keys and control the opening of the touchpad!

**Comment by user501254** [comment] 2018-04-11 05:00
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/23

**Closed by user501254** 2018-04-11 05:00 UTC
Labels: duplicate, enhancement
