### ISSUE TITLE
Touchscreen not detected (Ubuntu 17.10)

### ISSUE THREAD

**Issue by chandanand** [user501254/TouchpadIndicator#22] opened 2017-10-25 20:27 UTC
Hi,

I am using Dell XPS 13. Earlier I was using ubuntu and the indicator worked fine. After switching to Ubuntu 17.10, the indicator is not detecting touchscreen.

**Comment by user501254** [comment] 2017-11-06 09:14
Hi @chandanand 
I believe Ubuntu 17.10 (Artful Aardvark) now comes with the Gnome Shell and there's already an open issue where  touch screen is not detected by the extension in newer version of GNOME.
Can you please confirm the Ubuntu version you were using earlier (under which the touchscreen was detected)?

**Comment by chandanand** [comment] 2017-11-07 01:44
I was using Ubuntu Gnome 17.04.

**Comment by kitingChris** [comment] 2018-01-29 12:02
Looks like the same issue with #11

**Comment by user501254** [comment] 2018-03-31 06:18
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/11.

**Closed by user501254** 2018-03-31 06:18 UTC
Labels: duplicate
