### ISSUE TITLE
Please add option for shortcut On Off

### ISSUE THREAD

**Issue by biji** [user501254/TouchpadIndicator#12] opened 2017-02-13 07:18 UTC
My mouse is wireless, and usb dongle is always plugged, so auto detection will fail. Please add option for shortcut to turn on/off touchpad manually

thanks

**Comment by user501254** [comment] 2017-08-01 19:41
@biji 
Is it a wireless mouse with a separate dongle or does it rely on your PC's bluetooth?

**Comment by user501254** [comment] 2018-03-31 06:57
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/23

**Closed by user501254** 2018-03-31 06:57 UTC
Labels: duplicate
