### ISSUE TITLE
Touchscreen not detected

### ISSUE THREAD

**Issue by pointhi** [user501254/TouchpadIndicator#18] opened 2017-07-24 12:29 UTC
```
$ cat /proc/bus/input/devices | grep -i touch -A8 -E1
I: Bus=0003 Vendor=04f3 Product=21d5 Version=0110
N: Name="ELAN Touchscreen"
P: Phys=usb-0000:00:14.0-9/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/0003:04F3:21D5.0003/input/input4
U: Uniq=
H: Handlers=event3 mouse2 
B: PROP=2
B: EV=b
B: KEY=400 0 0 0 0 0
B: ABS=3273800000000003
--
I: Bus=0011 Vendor=0002 Product=0007 Version=01b1
N: Name="SynPS/2 Synaptics TouchPad"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input15
U: Uniq=
H: Handlers=event12 mouse3 
B: PROP=5
B: EV=b
B: KEY=e520 10000 0 0 0 0
B: ABS=660800011000003
--
I: Bus=0018 Vendor=06cb Product=7a13 Version=0100
N: Name="DLL06E4:01 06CB:7A13 Touchpad"
P: Phys=i2c-DLL06E4:01
S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-17/i2c-DLL06E4:01/0018:06CB:7A13.0006/input/input19
U: Uniq=
H: Handlers=event14 mouse4 
B: PROP=5
B: EV=b
B: KEY=e520 10000 0 0 0 0
B: ABS=260800000000003
```

Looking into the debug window, only the touchpads are detected:

```
Gnome Shell Version: 3.24.3
Touchpad Indicator Version: 28
Touchpad(s): SynPS/2 Synaptics TouchPad | DLL06E4:01 06CB:7A13 Touchpad
Synclient: Nicht gefunden oder nicht auf dem System installiert.
Xinput: Ist installiert.
Umschaltmethode: Gconf
```

**Comment by user501254** [comment] 2017-08-01 18:42
Hi @pointhi 
Could you please also provide `xinput` output?

**Comment by pointhi** [comment] 2017-08-01 19:29
user501254: that's not possible in the next weeks, because I'm on holiday and that's the laptop I use for work.

**Comment by user501254** [comment] 2017-08-01 19:32
Alright, from when exactly are you facing this issue?

**Comment by pointhi** [comment] 2017-08-01 20:59
The problem arrised after a gnome update (I think from 2.22  to 2.24)

**Comment by pointhi** [comment] 2017-11-10 09:33
```
$ xinput 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:14                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:14            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-touch:14                       	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:14                    	id=8	[slave  keyboard (3)]
```

**Comment by user501254** [comment] 2018-03-31 07:14
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/11

**Closed by user501254** 2018-03-31 07:14 UTC
Labels: bug, duplicate
